### ISSUE TITLE
Getting error when running README example. 

### ISSUE THREAD

**Issue by henrydot** [philou/complexity-assert#1]
I am getting the error "expected #<LinearSearch:0x007f93cbb8d9e8> to respond to `linear?`" when attempting to run the example from the README as a test. 

My code is literally copied from the README. I am getting the same errror when I run the specs for my actual code as well. Any help is much appreciated!

Spec file:

```
class LinearSearch

  # Generate some arguments of a particular size
  def generate_args(size)
    [ Array.new(size) { rand(1..size) }, rand(1..size) ]
  end

  # Run the code on which we want to assert performance
  def run(array, searched)
    found = false;
    array.each do |element|
      if element == array
        found = true
      end
    end
    found
  end
end

describe "Linear search" do

  it "performs linearly" do
    # Verify that the code runs in time proportional to the size of its arguments
    expect(LinearSearch.new).to be_linear()
  end

end
```

**Comment by philou** [comment]
Hi thanks for trying out my little gem. It seems you are missing the require directive. Try to add that at the begining of your file `require 'complexity_assert'`.

I also noticed that I had forgotten to publish the gem to rubygem, that's now fixed ... bundler should run a lot better now !

**Comment by henrydot** [comment]
Great! I knew it had to be something simple like that. Thats got it working. Thanks for creating this!
